# Generated by Django 3.0.5 on 2020-11-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defore_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('defore_time', models.CharField(blank=True, max_length=255, null=True)),
                ('defore_fmimg', models.CharField(blank=True, max_length=255, null=True)),
                ('defore_img', models.CharField(blank=True, max_length=255, null=True)),
                ('defore_str', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Defore_data',
                'managed': True,
            },
        ),
    ]
