# Generated by Django 3.0.5 on 2020-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qing', '0003_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
