# Generated by Django 3.0.5 on 2020-11-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qing', '0004_data_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片标题'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='原文链接'),
        ),
        migrations.AlterField(
            model_name='defore_data',
            name='defore_fmimg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='defore_data',
            name='defore_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='完成的图片路径'),
        ),
        migrations.AlterField(
            model_name='defore_data',
            name='defore_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='defore_data',
            name='defore_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='mistakes',
            name='mistakes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='错误日志'),
        ),
    ]
